Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -23,27 +23,32 @@ permissions:
 concurrency:
   group: "pages"
   cancel-in-progress: false
-
-jobs:
-  # Build job
+  jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - name: Detect package manager
         id: detect-package-manager
         run: |
-    if [ -f "${{ github.workspace }}/yarn" ]; then
-      echo "manager=yarn" >> $GITHUB_OUTPUT
-      echo "command=install" >> $GITHUB_OUTPUT
-      echo "runner=yarn" >> $GITHUB_OUTPUT
-    else
-      echo "manager=npm" >> $GITHUB_OUTPUT
-      echo "command=ci" >> $GITHUB_OUTPUT
-      echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-    fi
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
           fi
+
+          
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
